#!/usr/bin/env bash

xrdb -merge ~/.Xresources
pidof st | xargs kill -s USR1
ln -sf ~/.cache/wal/roficolors/pywal.rasi ~/.config/rofi/colors/pywal.rasi
ln -sf ~/.cache/wal/dunst ~/.config/dunst
ln -sf ~/.cache/wal/picom/shadow.conf ~/.config/picom/shadow.conf
ln -sf ~/.cache/wal/gtk.css ~/.config/gtk-3.0/gtk.css
ln -sf ~/.cache/wal/gtk.css ~/.config/gtk-4.0/gtk.css
pkill dunst; setsid -f dunst

# 1. Define the path to your qutebrowser executable
QUTE_BIN="$HOME/qute-py/.venv/bin/python3 -m qutebrowser"

# 2. Check if qutebrowser is running
if pgrep -f "qutebrowser" > /dev/null; then
    # 3. Use the running instance to source the new colors
    $QUTE_BIN ':config-source'
fi

# Refresh all running Neovim/LunarVim instances
for server in /tmp/nvimsocket*; do
    [ -S "$server" ] && nvim --server "$server" --remote-send '<Esc>:colorscheme wal<CR>' &
done

sleep 0.5

notify-send "Wallpaper changed"
