#!/usr/bin/env bash

xrdb -merge ~/.Xresources
pidof st | xargs kill -s USR1
ln -sf ~/.cache/wal/roficolors/pywal.rasi ~/.config/rofi/colors/pywal.rasi
ln -sf ~/.cache/wal/dunst ~/.config/dunst
ln -sf ~/.cache/wal/picom/shadow.conf ~/.config/picom/shadow.conf
ln -sf ~/.cache/wal/gtk.css ~/.config/gtk-3.0/gtk.css
ln -sf ~/.cache/wal/gtk.css ~/.config/gtk-4.0/gtk.css
pkill dunst; setsid -f dunst

QUTE_BIN="$HOME/qute-py/.venv/bin/python3 -m qutebrowser"
if pgrep -f "qutebrowser" > /dev/null; then
    $QUTE_BIN ':config-source'
fi

for server in /tmp/nvimsocket*; do
    [ -S "$server" ] && nvim --server "$server" --remote-send '<Esc>:colorscheme wal<CR>' &
done

sleep 0.5
notify-send "Wallpaper changed"

# updates lockscreen
rm /tmp/screenlock.png
# betterlockscreen -u `cat ~/.cache/wal/wal`
notify-send "lockscreen has been updated"
